# Generated by Django 5.0.2 on 2024-02-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_married',
            field=models.BooleanField(null=True),
        ),
    ]
